import { Question, PersonalityType } from './types';

// Данные для подключения к Supabase
export const SUPABASE_URL = 'https://euxcdlyrgvunxxoxthcw.supabase.co';
export const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV1eGNkbHlyZ3Z1bnh4b3h0aGN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY2NzY1ODAsImV4cCI6MjA4MjI1MjU4MH0.uk4brYo2L8gfVEYTH723tMcl-0mfhNa5giqFxqvG1jw';

// Gemini API Key (Вставьте ваш ключ ниже)
export const GEMINI_API_KEY = 'YOUR_GEMINI_API_KEY';

export const INTERESTS_LIST = [
  "Спорт",
  "Рукоделие",
  "Музыка",
  "Интернет / Соцсети",
  "Чтение / Книги",
  "Дача / Садоводство",
  "Вязание / Шитье",
  "Видеоигры",
  "Рисование",
  "Кулинария",
  "Фотография",
  "Авто / Мото",
  "Ремонт / DIY",
  "Дом / Интерьер",
  "Путешествия",
  "Питомцы",
  "Дети / Семья",
  "Танцы",
  "Театр / Кино",
  "Огород / Цветоводство",
  "Коллекционирование",
  "IT / Гаджеты",
  "Йога",
  "Бизнес / Финансы",
  "Языки",
  "Психология",
  "Столярство / Дерево",
  "Настолки / Квизы",
  "Рыбалка / Охота",
  "Юмор / Стендап",
  "Ювелирка",
  "Спа",
  "Садоводство",
  "Косметика",
  "Бьюти",
  "Красота",
  "Зоология",
  "Астрономия",
  "Мода",
  "Дизайн",
  "Декор",
  "Мебель",
  "История",
  "География",
  "Эзотерика",
  "Магия",
  "Ауры",
  "Энергия",
  "Медитация",
  "Электроника"
];

export const BUBBLE_COLORS = [
  "bg-blue-100 text-blue-800 border-blue-200",
  "bg-green-100 text-green-800 border-green-200",
  "bg-purple-100 text-purple-800 border-purple-200",
  "bg-pink-100 text-pink-800 border-pink-200",
  "bg-yellow-100 text-yellow-800 border-yellow-200",
  "bg-orange-100 text-orange-800 border-orange-200",
  "bg-teal-100 text-teal-800 border-teal-200",
  "bg-indigo-100 text-indigo-800 border-indigo-200",
];

export const QUESTIONS: Question[] = [
  { id: 1, scale: 'JP', optionA: "Составляю списки", optionB: "Полагаюсь на память" },
  { id: 2, scale: 'FT', optionA: "Скептически настроен", optionB: "Хочу верить" },
  { id: 3, scale: 'EI', optionA: "Скучаю, оставаясь в одиночестве", optionB: "Нуждаюсь бывать в одиночестве" },
  { id: 4, scale: 'SN', optionA: "Принимаю вещи такими, какие они есть", optionB: "Недоволен положением вещей" },
  { id: 5, scale: 'JP', optionA: "Поддерживаю порядок в комнате", optionB: "Разбрасываю вещи, как придется" },
  { id: 6, scale: 'FT', optionA: "Сравнение с роботом было бы для меня обидным", optionB: "Стремлюсь мыслить, как механизм" },
  { id: 7, scale: 'EI', optionA: "Энергичный", optionB: "Мягкий" },
  { id: 8, scale: 'SN', optionA: "Предпочту пройти тест с вариантами ответов", optionB: "Предпочту написать эссе" },
  { id: 9, scale: 'JP', optionA: "Хаотичный", optionB: "Организованный" },
  { id: 10, scale: 'FT', optionA: "Легкоранимый", optionB: "Толстокожий" },
  { id: 11, scale: 'EI', optionA: "Лучше работаю в коллективе", optionB: "Лучше работаю самостоятельно" },
  { id: 12, scale: 'SN', optionA: "Сфокусирован на настоящем", optionB: "Сфокусирован на будущем" },
  { id: 13, scale: 'JP', optionA: "Планирую далеко вперед", optionB: "Решаю в последнюю минуту" },
  { id: 14, scale: 'FT', optionA: "Хочу, чтобы меня уважали", optionB: "Хочу, чтобы меня любили" },
  { id: 15, scale: 'EI', optionA: "Вечеринки меня утомляют", optionB: "Заряжаюсь бодростью на вечеринках" },
  { id: 16, scale: 'SN', optionA: "Вписываюсь в коллектив", optionB: "Держусь особняком" },
  { id: 17, scale: 'JP', optionA: "Оставляю за собой свободу выбора", optionB: "Беру на себя обязательства" },
  { id: 18, scale: 'FT', optionA: "Хочу уметь чинить вещи", optionB: "Хочу уметь исправлять людей" },
  { id: 19, scale: 'EI', optionA: "Больше говорю", optionB: "Больше слушаю" },
  { id: 20, scale: 'SN', optionA: "Описывая событие, расскажу, что происходило", optionB: "Описывая событие, расскажу, в чем его смысл" },
  { id: 21, scale: 'JP', optionA: "Выполняю работу сразу же", optionB: "Откладываю работу на потом" },
  { id: 22, scale: 'FT', optionA: "Слушаю сердце", optionB: "Слушаю рассудок" },
  { id: 23, scale: 'EI', optionA: "Домосед", optionB: "Провожу время вне дома" },
  { id: 24, scale: 'SN', optionA: "Хочу видеть общую картину", optionB: "Хочу видеть детали" },
  { id: 25, scale: 'JP', optionA: "Импровизирую", optionB: "Тщательно готовлюсь" },
  { id: 26, scale: 'FT', optionA: "Основа морали – справедливость", optionB: "Основа морали – сострадание" },
  { id: 27, scale: 'EI', optionA: "Громко кричать для меня проблема", optionB: "Запросто крикну человеку в отдалении" },
  { id: 28, scale: 'SN', optionA: "Теоретик", optionB: "Практик" },
  { id: 29, scale: 'JP', optionA: "Делаю дело", optionB: "Гуляю смело" },
  { id: 30, scale: 'FT', optionA: "Испытываю дискомфорт от эмоций", optionB: "Ценю эмоции" },
  { id: 31, scale: 'EI', optionA: "Люблю выступать перед людьми", optionB: "Избегаю говорить на публику" },
  { id: 32, scale: 'SN', optionA: "Хочу знать «что?», «где?», «когда?»", optionB: "Хочу знать «почему?»" },
];

export const PERSONALITY_TYPES: Record<string, PersonalityType> = {
  'ISTJ': { code: 'ISTJ', name: 'Администратор', description: 'Практичные и ответственные, ценят традиции и порядок.' },
  'ISFJ': { code: 'ISFJ', name: 'Защитник', description: 'Преданные и теплые защитники, всегда готовы поддержать близких.' },
  'INFJ': { code: 'INFJ', name: 'Активист', description: 'Тихие и мистические, но при этом очень вдохновляющие идеалисты.' },
  'INTJ': { code: 'INTJ', name: 'Стратег', description: 'Богатые воображением и стратегические мыслители с планом на всё.' },
  'ISTP': { code: 'ISTP', name: 'Виртуоз', description: 'Смелые и практичные экспериментаторы, мастера на все руки.' },
  'ISFP': { code: 'ISFP', name: 'Артист', description: 'Гибкие и очаровательные художники, всегда готовы исследовать новое.' },
  'INFP': { code: 'INFP', name: 'Посредник', description: 'Поэтичные, добрые и альтруистичные люди, ищущие гармонию.' },
  'INTP': { code: 'INTP', name: 'Ученый', description: 'Инновационные изобретатели с неутолимой жаждая знаний.' },
  'ESTP': { code: 'ESTP', name: 'Делец', description: 'Умные, энергичные и очень проницательные люди, любящие риск.' },
  'ESFP': { code: 'ESFP', name: 'Развлекатель', description: 'Спонтанные, энергичные и неутомимые оптимисты.' },
  'ENFP': { code: 'ENFP', name: 'Борец', description: 'Энтузиасты, творческие и общительные свободные души.' },
  'ENTP': { code: 'ENTP', name: 'Полемист', description: 'Умные и любопытные мыслители, которые не могут устоять перед интеллектуальным вызовом.' },
  'ESTJ': { code: 'ESTJ', name: 'Менеджер', description: 'Отличные администраторы, непревзойденные в управлении вещами или людьми.' },
  'ESFJ': { code: 'ESFJ', name: 'Консул', description: 'Необычайно заботливые, общительные и популярные люди, всегда готовые помочь.' },
  'ENFJ': { code: 'ENFJ', name: 'Тренер', description: 'Харизматичные и вдохновляющие лидеры, способные заворожить своих слушателей.' },
  'ENTJ': { code: 'ENTJ', name: 'Командир', description: 'Смелые, с богатым воображением и сильной волей лидеры, всегда находящие путь или прокладывающие его.' },
};